name: flutter_init_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  drift: ^2.29.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  hooks_riverpod: ^3.0.3
  path: ^1.9.1
  path_provider: ^2.1.4
  json_annotation: ^4.9.0
  sqlite3: ^2.9.4
  riverpod_annotation: ^3.0.3
  sqlite3_flutter_libs: ^0.5.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  drift_dev: ^2.29.0
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
